//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtoCommerce.OrderModule.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrderResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtoCommerce.OrderModule.Data.Resources.OrderResources", typeof(OrderResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address &apos;{2}&apos; for {0} {1} added.
        /// </summary>
        internal static string AddressAdded {
            get {
                return ResourceManager.GetString("AddressAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address &apos;{2}&apos; for {0} {1} deleted.
        /// </summary>
        internal static string AddressRemoved {
            get {
                return ResourceManager.GetString("AddressRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new {0} {1} added.
        /// </summary>
        internal static string OperationAdded {
            get {
                return ResourceManager.GetString("OperationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment changed for {0} {1}.
        /// </summary>
        internal static string OperationCommentChanged {
            get {
                return ResourceManager.GetString("OperationCommentChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} {1} deleted.
        /// </summary>
        internal static string OperationDeleted {
            get {
                return ResourceManager.GetString("OperationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} {1} status changed from &apos;{2}&apos; to &apos;{3}&apos; .
        /// </summary>
        internal static string OperationStatusChanged {
            get {
                return ResourceManager.GetString("OperationStatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} {1} total changed from {2} to {3}.
        /// </summary>
        internal static string OperationTotalChanged {
            get {
                return ResourceManager.GetString("OperationTotalChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order employee was changed  to &apos;{0}&apos;.
        /// </summary>
        internal static string OrderEmployeeChanged {
            get {
                return ResourceManager.GetString("OrderEmployeeChanged", resourceCulture);
            }
        }
    }
}
